export const HOME_SUCCESS = 'HOME_SUCCESS';

// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_USER_SESSION = 'SET_USER_SESSION';
export const CLEAR_SESSION = 'CLEAR_SESSION';

// CASILLA
export const GET_CASILLAS = 'GET_CASILLAS';
export const GET_CASILLAS_ERROR = 'GET_CASILLAS_ERROR';

// SECCION
export const GET_SECCIONES = 'GET_SECCIONES';
export const GET_SECCIONES_ERROR = 'GET_SECCIONES_ERROR';

//PROMOVIDOS
export const GET_PROMOVIDOS = 'GET_PROMOVIDOS';
export const PUT_PROMOVIDOS = 'PUT_PROMOVIDOS';
export const CLEAN_PROMOVIDOS = 'CLEAN_PROMOVIDOS';
export const GET_PROMOVIDOS_ERROR = 'GET_PROMOVIDOS_ERROR';
// CAMERA
export const SAVE_PHOTO = 'SAVE_PHOTO';
export const CLEAR_PHOTO = 'CLEAR_PHOTO';

